### ISSUE TITLE
Hi Jared I'm interested to your project theatreticket

### ISSUE THREAD

**Issue by giumazzi** [XiTickets/TheatreTickets#2]
Hi Jared,
I’m a member of an italian amatorial theatre group (www.ilguitto.org) that once a year, for 4 or 5 days, plays a comedy.
In those days we have the need to allow our public to book some ticket in advance.
My Idea is to implement a simple form In PHP, starting from the map, to send to a mysql db all the data, so one person can book seats and the person after can see that some seats are now unavailable (no paypal gateway)
Below you can see an example
![map](https://cloud.githubusercontent.com/assets/25555987/23252334/c8ba434c-f9b0-11e6-8363-96be67f85b77.jpg)

I’have understood quite well the seat chart js but I don’t understand how to implement something like this 
I’ve seen your project but  I’ve not seen php pages.

Can You help me?

Thanks for everything you can suggest to us

**Comment by computerwizjared** [comment]
@giumazzi I'm sorry, but this project is old and I'm not able to support it nor keep it up to date. I was trying to work on a new version called "XiTickets", however it did not pan out.
